### ISSUE TITLE
loading Page ...

### ISSUE THREAD

**Issue by jayendrapawar** [codeTIT4N/supply-chain-truffle-react#1]
Uploading Pharma Supply Chain - Google Chrome 2022-04-28 17-21-04.mp4…

setCurrentaccount is also set properly all things are going right but there is still setloader value is not changing

**Comment by codetit4n** [comment]
Hey @JPcodebeast can you provide me some more information regarding the issue. It is not clear here

**Comment by jayendrapawar** [comment]
https://user-images.githubusercontent.com/61478029/165758103-1dbdb629-486a-4a6e-8503-0b790b525920.mp4

**Comment by jayendrapawar** [comment]
Video is attached. I clicked on register after local setup ....its stuck on
loading page .

**Comment by jayendrapawar** [comment]
@codeTIT4N.... .whole problem is shown in video.. tell if any issue on setup done is there .... @codeTIT4N  thanks for early replies and help.

**Comment by codetit4n** [comment]
Hey @JPcodebeast  I wasn't able to reproduce the issue it was working fine on my system. 

Did you install Ganache and switch your metamask network to RPC: 127.0.0.1:7545 ?

**Comment by jayendrapawar** [comment]
Yes, I did that.
 Can you do one favour for me?
Just send me screen recording of local setup.

**Comment by jayendrapawar** [comment]
Can we talk on call ?
****** Jayendra Pawar

**Comment by codetit4n** [comment]
your email?

**Comment by jayendrapawar** [comment]
***@***.***

**Comment by jayendrapawar** [comment]
Reply !?

**Comment by codetit4n** [comment]
can't see your mail GitHub must have hidden it. Will msg you on whatsapp

**Comment by codetit4n** [comment]
since this issue was resolved i am closing it. I have hidden your number @JPcodebeast .

**Comment by abinashdhungana** [comment]
Hello, @codeTIT4N  I'm stuck at certain point need help!!!

**Comment by jayendrapawar** [comment]
What happened?

**Comment by ghost** [comment]
Please what is the solution to this problem
