### ISSUE TITLE
I'm stuck.

### ISSUE THREAD

**Issue by abinashdhungana** [codeTIT4N/supply-chain-truffle-react#2]
Hello, @codeTIT4N could you help me I got stuck at a certain phase. SS is below. Could you please provide me with your whats app number so we chat.
![image](https://user-images.githubusercontent.com/107915328/175349527-089300ed-4911-4afe-9799-d187cf35e140.png)

**Comment by codetit4n** [comment]
hey @abinashdhungana here is my linkedin: https://www.linkedin.com/in/lokesh-kumar-nalot-0baa691b9/ msg me there. I'll give you my whatsapp number

**Comment by abinashdhungana** [comment]
> hey @abinashdhungana here is my linkedin: https://www.linkedin.com/in/lokesh-kumar-nalot-0baa691b9/ msg me there. I'll give you my whatsapp number

Hello Sir, I have sent you a request on linkedin.
Thank you!!
